/** Mondomatic */

#ifndef _HEAVY_CONTEXT_DEARMONDO610_HPP_
#define _HEAVY_CONTEXT_DEARMONDO610_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvControlSlice.h"
#include "HvControlUnop.h"
#include "HvControlVar.h"
#include "HvControlSystem.h"
#include "HvControlDelay.h"
#include "HvControlCast.h"
#include "HvSignalLine.h"
#include "HvSignalBiquad.h"
#include "HvSignalDel1.h"
#include "HvMath.h"
#include "HvSignalVar.h"
#include "HvControlBinop.h"
#include "HvSignalRPole.h"

class Heavy_DeArmondo610 : public HeavyContext {

 public:
  Heavy_DeArmondo610(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_DeArmondo610();

  const char *getName() override { return "DeArmondo610"; }
  int getNumInputChannels() override { return 1; }
  int getNumOutputChannels() override { return 1; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;
  struct Parameter {
    struct In {
      enum ParameterIn : hv_uint32_t {
        EMPHASIS = 0x5C18FB0F, // Emphasis
        PEDAL = 0x4980B0E2, // Pedal
        TONESWEEP = 0x22A27CE7, // ToneSweep
        VOLUMEMIN = 0x927FE933, // VolumeMin
      };
    };
  };

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;


  /*
  * Code for expr~ implementation
  * Write out the generic header code
  */

  // per class code

  // per object code


  // static sendMessage functions
  static void cMsg_ibAc8sI4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_2NaXKI2g_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_tpS6VyvF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_vgdjzrMq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nGaLaCvp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_6XCSelAf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_T49zkRsX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TyC30dgY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_F7KoASf0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BTLd5E5y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QkaX8nvi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dk45xhZN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_geeN8rbV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_0i7vKp02_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_w6Wo1rdt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_bWyvdF7a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YbvRIVae_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5c6JS06k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lIqQyAob_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_soG53KQW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zjDmfbTe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6NTrhA7w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_T3iReJAq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EIEr1h0l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_iolKsZWN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_gGfFz0dm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_WrTuu5px_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_194zqgUv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0GrKpQrj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_F2ixJJtv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_B8zLAd5H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_yRAMgNEV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_OdD88Ij3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_a0F7GXKK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wvx05EMO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nkDJpOnn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PlAHsac6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_op6xj9DK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_e7hDkuvj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_J3JjZzMZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UbZjH1rz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9pXPIRrj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_LyNfoDwj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_eFrx2lrI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NlSrmQgp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_pu6eikCK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qYd9iFrw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_TB4C0sGQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_e08vW7kZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dspJZwD6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0y1OKiwQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kEbTkRZx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_4eZJP2PB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_bvF00zqi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_BNqeNdGO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ip6gY18c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JcwPRLUH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_71IcMDyL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_OPGuCbaW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KnjyEWuF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nA4GED2p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SG367RHT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aEvayMrL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_RBk64CK5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SvjF01Ry_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_UtOmNvrf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_DVR8ZTOi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Q5LGjP9s_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_iiPcK6iI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_RLkBNTU3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_YHoVC904_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_2jWpitlR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_2c9WEzyw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_th0UKfUk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_m12lKK3r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xzPj9ewH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_62cZukjg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_X6EQs84p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_JmRLOAfP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AsFLhwUE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_h8XW9AVS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0npyXMt1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_miVN89gx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7pxirQIx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SxdxgfFE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_x7vLP1rb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EyVYiFqH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_83wmxcoK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4UDqhOjY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_FSOXXmUz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aWLk8hbc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Kl8gIZSl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5MMx6wEm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wfVr0Sx0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6OA9GWUK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_domtT09M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_9y8OmpFL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_eAbR69ux_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_DJL5NUeh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_YWSd7ce4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_oHq0ZN3I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_znNTnENy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_MrxAshFX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_vfegZkXu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uN2wfzZd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FKJBiyfl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QAt4N8Js_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_H9rUn0Dr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SZFpXE7V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SKSSL040_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_X2mvDOaz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_25OA0F3b_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wQJ45YTJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_k82a7NRb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xr6Wlslb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_uamuzMoV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kO70kUxS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tnt3Hpco_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gWLvns7F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Z5WcZ84i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_7aE6hxjg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1v1apkHX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qx2C9IVU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_7r2Zd8HV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fDk545QO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WCxX1Yq2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_G8rqCBul_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5jhITf4O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XmvO31fH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_tD3pauSZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_rPt8fxzY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_7p64I2mW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_47Z3ykh1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0HYvsPww_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vpsJByp3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MArswka4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_57F2HP6D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_AYj6GVw7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_qW4KKbwR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_alBHzhXn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QYcNP4L0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gC1bOJjN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NM97Tk4A_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_74SiTy2N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_LkbRaMT4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_S873RPP3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_MpXArC5k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_81HXfgny_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_okuVQsIK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JkpthQ1w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kvyxwhtj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TA58Paz7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vohOND6k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_OlS4wU7p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SCtMdJ0i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_bXlN32Bn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YfxcQMmj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_eqgbAqUF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tD99ueDq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2JGBzhNO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_MJKTv0rP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_YMywvVQl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_Gxouw1Td_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WhPj2tyL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pnfx0uFA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Zy6Fo9qS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_bNeqsg8e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_sMVMQyay_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_88UpINYT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_x1NprS8k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ajO39xET_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GjuMlJwF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_juzSwQ1U_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_IknXE25s_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BDFZR6ZK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_S2mE3b0D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_w5xI5ZRE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_UvoOgL4H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6piFiTns_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_44yqlhm1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_glndyNXh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mzdG8QPX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_pQALY3Ch_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_b6Tzf6g8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_aJO95iAo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_Mn4A0Ipa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_GgoCB1BF_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_CYOqdQn2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9UsR2dbA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JZ0dH7Nu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_m9KZmITC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_EE1EgnzF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PloATMYU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_f3lYAkkl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JSrK2UBW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jkBc2ZAY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_jyVPemfq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_jm60M47o_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_8kC92MA3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZA98e4Ps_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_IThBhHsN_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_UVcf7idu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_qB4wTzTa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_M1X1btE2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_5KuxpKRv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_214Ay9F2_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_iKantOVi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_JO1ZmvWT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_4A1IIwH6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Tcf60p6V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_bJP3Ky4I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_BkgUSWdx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_eHRShi44_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xw9Rv0lO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TUdblxuX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Sfc8KcKK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KXFPbnkN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ue99Y3kY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TvLjI6kz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0l9JX8Lu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4gIq0LyG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xshzef0s_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Mr0LQUnj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4nnJqXig_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_alr5k3jx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_eFbHMIp6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kVzBDlWT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9MpYqnPY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_co3XDqdt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vjmftykI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_w1JHAPti_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_l0sSAHGG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9EGF00gU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_d6QKfOLy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_OBHpqGt3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AF27zXCC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_M3RKxis0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NEPyqdvw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oJGseYd0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xbVik2iy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_az688FC8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_hvWCerxa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_GiDFJQx6_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_jkECiwzJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_uCDsn2Px_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Q8Mns5ww_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_12OGtY9i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_baMdQ0Wc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EmhbNNf2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_V6CD8tME_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XgmgeQbk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Y9QD7s7r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_B77hUP9z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_LciiDc9k_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_INokwpZW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qf0b5war_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_X7mr3Eoi_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_6zoQHZ0I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_GJp2IGWb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_QB5URDyc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_gE4L627F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_9wh66raz_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_oA0hJOFz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_3KLVPd3b_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_a73Gbt08_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_9hDxfFUq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_iOq1DlDM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_C44HTvgg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3YVdHAMY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Rlogjs4P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ilFk30UF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_f7BfkyBr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zDsYzfux_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_gA89Dp2N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pVQjCkid_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_J1SY10zY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jJDY2AlA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8GPWrX3M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2w2BCMNq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_w95DPuWQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3f7TBWZD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_lwLwhbp5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_MWI35sgk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_k1EIknf9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qNujzWIg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZkEKrw5C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_C7ap9d2f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_sgo9a43j_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9Sssgwhf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_n9GzENNS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_64saYHmD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mmMLozEp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fpEDEadH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_M5aujGBv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9FsWP10L_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_aMF7PZBG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CY1Wkaj5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AERBaP9z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yrLTC5YK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ElByyEk4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oYPGbnFu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rb3YYE79_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NlQqtqTj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wzzV5yjn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_asS5PPmF_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_OaR2IZS3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_D58GPniR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_tJpVUJK0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_23hxPkrt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_z6x1x8gn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zaHUw3i6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EIswnuhw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_PO3pIZH5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_t8RvmQCe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_PWx9uxnM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_M1Xb3YFr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xrZ0XYAH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_BcDsdKtt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_d1OL8GIX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qwLwfjDC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_27AtVIgv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gac6qAMI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_UQfzBJAS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FjtCaWxH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_n0tLGvv0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_cdkR8Sxe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_0qASSksN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_dQMpRuqS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_HV9O5ipP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_uZs4FwvW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_GczMPxbd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_NXRTxdw9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_VRcYDHaJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_TRLTp0Vw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_xTeBXKdv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_FYIp5EIA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_fIp0FVAO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_wMgYECKc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_q9tK5JGo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_jwxflMvx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_2soygJv4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_bbWehlk8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_7VLNZRf9_sendMessage(HeavyContextInterface *, int, const HvMessage *);

  // objects
  SignalRPole sRPole_YesGgUOP;
  SignalDel1 sDel1_YdAGvNEr;
  SignalLine sLine_RG7iNc1h;
  SignalLine sLine_JU0q3cFQ;
  SignalLine sLine_0jZdO376;
  SignalLine sLine_r7LEgU0Y;
  SignalBiquad sBiquad_s_ZW3s5Bm1;
  SignalLine sLine_wP0NBA9m;
  SignalLine sLine_fhsCyCCZ;
  SignalLine sLine_IvdoPNmi;
  SignalLine sLine_ESio21H0;
  SignalLine sLine_LGUfYgPN;
  SignalBiquad sBiquad_s_K2WTNYNZ;
  SignalLine sLine_pe12TLXC;
  SignalLine sLine_eSPpmIGJ;
  SignalLine sLine_Z3SNB2ul;
  SignalLine sLine_vWXddGR2;
  SignalLine sLine_3zFX6gWY;
  SignalBiquad sBiquad_s_pmXdn4xr;
  ControlBinop cBinop_F7KoASf0;
  ControlBinop cBinop_QkaX8nvi;
  ControlBinop cBinop_dk45xhZN;
  ControlBinop cBinop_w6Wo1rdt;
  ControlBinop cBinop_bWyvdF7a;
  ControlBinop cBinop_YbvRIVae;
  ControlBinop cBinop_5c6JS06k;
  ControlBinop cBinop_lIqQyAob;
  ControlBinop cBinop_soG53KQW;
  ControlBinop cBinop_zjDmfbTe;
  ControlBinop cBinop_6NTrhA7w;
  ControlBinop cBinop_EIEr1h0l;
  ControlVar cVar_iolKsZWN;
  ControlVar cVar_gGfFz0dm;
  ControlVar cVar_WrTuu5px;
  ControlBinop cBinop_a0F7GXKK;
  ControlBinop cBinop_wvx05EMO;
  ControlBinop cBinop_nkDJpOnn;
  ControlBinop cBinop_op6xj9DK;
  ControlBinop cBinop_e7hDkuvj;
  ControlBinop cBinop_J3JjZzMZ;
  ControlBinop cBinop_UbZjH1rz;
  ControlBinop cBinop_9pXPIRrj;
  ControlBinop cBinop_0y1OKiwQ;
  ControlBinop cBinop_kEbTkRZx;
  SignalVarf sVarf_6rRXIaYv;
  ControlVar cVar_4eZJP2PB;
  ControlBinop cBinop_Ip6gY18c;
  ControlBinop cBinop_JcwPRLUH;
  ControlBinop cBinop_OPGuCbaW;
  ControlBinop cBinop_KnjyEWuF;
  ControlBinop cBinop_nA4GED2p;
  ControlBinop cBinop_SG367RHT;
  ControlBinop cBinop_aEvayMrL;
  SignalVarf sVarf_cacJeWDH;
  ControlVar cVar_RBk64CK5;
  ControlBinop cBinop_th0UKfUk;
  ControlBinop cBinop_xzPj9ewH;
  ControlBinop cBinop_62cZukjg;
  ControlBinop cBinop_AsFLhwUE;
  ControlBinop cBinop_h8XW9AVS;
  ControlBinop cBinop_0npyXMt1;
  ControlBinop cBinop_miVN89gx;
  ControlBinop cBinop_7pxirQIx;
  ControlBinop cBinop_x7vLP1rb;
  ControlBinop cBinop_83wmxcoK;
  ControlBinop cBinop_4UDqhOjY;
  ControlBinop cBinop_aWLk8hbc;
  ControlBinop cBinop_Kl8gIZSl;
  ControlBinop cBinop_5MMx6wEm;
  ControlBinop cBinop_6OA9GWUK;
  ControlVar cVar_domtT09M;
  ControlVar cVar_9y8OmpFL;
  ControlVar cVar_eAbR69ux;
  ControlBinop cBinop_uN2wfzZd;
  ControlBinop cBinop_FKJBiyfl;
  ControlBinop cBinop_QAt4N8Js;
  ControlBinop cBinop_SZFpXE7V;
  ControlBinop cBinop_SKSSL040;
  ControlBinop cBinop_X2mvDOaz;
  ControlBinop cBinop_25OA0F3b;
  ControlBinop cBinop_wQJ45YTJ;
  ControlBinop cBinop_k82a7NRb;
  ControlBinop cBinop_0HYvsPww;
  ControlBinop cBinop_MArswka4;
  ControlBinop cBinop_57F2HP6D;
  ControlBinop cBinop_alBHzhXn;
  ControlBinop cBinop_QYcNP4L0;
  ControlBinop cBinop_gC1bOJjN;
  ControlBinop cBinop_NM97Tk4A;
  ControlBinop cBinop_74SiTy2N;
  ControlBinop cBinop_S873RPP3;
  ControlBinop cBinop_81HXfgny;
  ControlBinop cBinop_okuVQsIK;
  ControlBinop cBinop_kvyxwhtj;
  ControlBinop cBinop_TA58Paz7;
  ControlBinop cBinop_vohOND6k;
  ControlBinop cBinop_SCtMdJ0i;
  ControlVar cVar_bXlN32Bn;
  ControlVar cVar_YfxcQMmj;
  ControlVar cVar_eqgbAqUF;
  ControlBinop cBinop_pnfx0uFA;
  ControlBinop cBinop_Zy6Fo9qS;
  ControlBinop cBinop_bNeqsg8e;
  ControlBinop cBinop_88UpINYT;
  ControlBinop cBinop_x1NprS8k;
  ControlBinop cBinop_ajO39xET;
  ControlBinop cBinop_GjuMlJwF;
  ControlBinop cBinop_juzSwQ1U;
  ControlBinop cBinop_IknXE25s;
  SignalVarf sVarf_sE1Hx9pA;
  ControlDelay cDelay_CYOqdQn2;
  ControlVar cVar_EE1EgnzF;
  ControlBinop cBinop_f3lYAkkl;
  ControlBinop cBinop_JSrK2UBW;
  ControlBinop cBinop_jkBc2ZAY;
  ControlVar cVar_jyVPemfq;
  ControlSlice cSlice_UVcf7idu;
  ControlSlice cSlice_qB4wTzTa;
  ControlVar cVar_M1X1btE2;
  ControlVar cVar_5KuxpKRv;
  ControlVar cVar_JO1ZmvWT;
  ControlVar cVar_4A1IIwH6;
  ControlVar cVar_Tcf60p6V;
  ControlSlice cSlice_bJP3Ky4I;
  ControlSlice cSlice_BkgUSWdx;
  ControlBinop cBinop_eHRShi44;
  ControlBinop cBinop_xw9Rv0lO;
  ControlBinop cBinop_TUdblxuX;
  ControlBinop cBinop_Sfc8KcKK;
  ControlBinop cBinop_KXFPbnkN;
  ControlBinop cBinop_0l9JX8Lu;
  ControlBinop cBinop_4gIq0LyG;
  ControlBinop cBinop_xshzef0s;
  ControlBinop cBinop_Mr0LQUnj;
  ControlBinop cBinop_vjmftykI;
  ControlBinop cBinop_AF27zXCC;
  ControlDelay cDelay_jkECiwzJ;
  ControlVar cVar_baMdQ0Wc;
  ControlBinop cBinop_V6CD8tME;
  ControlBinop cBinop_XgmgeQbk;
  ControlBinop cBinop_Y9QD7s7r;
  ControlVar cVar_B77hUP9z;
  ControlSlice cSlice_6zoQHZ0I;
  ControlSlice cSlice_GJp2IGWb;
  ControlVar cVar_QB5URDyc;
  ControlVar cVar_gE4L627F;
  ControlVar cVar_3KLVPd3b;
  ControlVar cVar_a73Gbt08;
  ControlVar cVar_9hDxfFUq;
  ControlSlice cSlice_iOq1DlDM;
  ControlSlice cSlice_C44HTvgg;
  ControlBinop cBinop_3YVdHAMY;
  ControlBinop cBinop_Rlogjs4P;
  ControlBinop cBinop_ilFk30UF;
  ControlBinop cBinop_f7BfkyBr;
  ControlBinop cBinop_zDsYzfux;
  ControlBinop cBinop_J1SY10zY;
  ControlBinop cBinop_jJDY2AlA;
  ControlBinop cBinop_8GPWrX3M;
  ControlBinop cBinop_2w2BCMNq;
  ControlBinop cBinop_ZkEKrw5C;
  ControlBinop cBinop_mmMLozEp;
  ControlBinop cBinop_CY1Wkaj5;
  ControlBinop cBinop_AERBaP9z;
  ControlVar cVar_yrLTC5YK;
  ControlVar cVar_ElByyEk4;
  ControlBinop cBinop_oYPGbnFu;
  ControlBinop cBinop_rb3YYE79;
  ControlBinop cBinop_NlQqtqTj;
  ControlBinop cBinop_wzzV5yjn;
  ControlVar cVar_tJpVUJK0;
  SignalVarf sVarf_cN18nVYk;
  ControlBinop cBinop_z6x1x8gn;
  ControlBinop cBinop_zaHUw3i6;
  ControlBinop cBinop_EIswnuhw;
  ControlBinop cBinop_M1Xb3YFr;
  ControlBinop cBinop_xrZ0XYAH;
};

#endif // _HEAVY_CONTEXT_DEARMONDO610_HPP_
