/** Mondomatic */

#ifndef _HEAVY_CONTEXT_DEARMONDO610_HPP_
#define _HEAVY_CONTEXT_DEARMONDO610_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvSignalBiquad.h"
#include "HvControlSlice.h"
#include "HvSignalLine.h"
#include "HvControlSystem.h"
#include "HvSignalRPole.h"
#include "HvSignalVar.h"
#include "HvMath.h"
#include "HvControlVar.h"
#include "HvControlIf.h"
#include "HvSignalDel1.h"
#include "HvControlCast.h"
#include "HvControlBinop.h"
#include "HvControlUnop.h"
#include "HvControlDelay.h"

class Heavy_DeArmondo610 : public HeavyContext {

 public:
  Heavy_DeArmondo610(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_DeArmondo610();

  const char *getName() override { return "DeArmondo610"; }
  int getNumInputChannels() override { return 1; }
  int getNumOutputChannels() override { return 1; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;
  struct Parameter {
    struct In {
      enum ParameterIn : hv_uint32_t {
        EMPHASIS = 0x5C18FB0F, // Emphasis
        OFFSET = 0x1A260E77, // Offset
        PEDAL = 0x4980B0E2, // Pedal
      };
    };
  };

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;


  /*
  * Code for expr~ implementation
  * Write out the generic header code
  */

  // per class code

  // per object code


  // static sendMessage functions
  static void cMsg_W8NjTHKk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_iC9kJrkL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_1AMUCUat_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_lFWwRqa3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8uCCHYmo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_fl5VKBJT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_BbcWGZUX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_0uvCj7Os_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8Vv93S17_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rCbnXIUj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0gs0arMJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MgRQ2ACv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_a7idr72d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_6LCBqyLE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xMSqkyVN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XMU1Tazm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nxgAiqc6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_r2APxwhJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1AxX65Et_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iPppAwO6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ToeTxfqO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ajn4g2hx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_4H0P7OhD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_eA3owBff_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_LrZYYuEo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_fG7Soiex_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8s6DX3g3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6XkCqo6d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_RiGXMOpz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_hgtO4f5q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_0aMoCy0W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_HlWcHx4F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_cvCZdbdm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Kp32kwPE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_47ZbPvx5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CEKzEfgQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YYmpYp2h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cC98FeJi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JGs3l7Zq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_eAUi692P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tJ8veD64_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5WqBImKu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FfowI9Ep_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gTfFpqz3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_57Q7NQr1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_OvAUiu7B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8ixc5MXh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_miskKPzL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fCPC5XIW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nrTl4Ds1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JRqpzz41_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_k0KmBsDI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_bgM6sZl2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jig9jByQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_leT89LkL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lnJMJnzS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pPeMaBtc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dm1cyrHg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yyfJyhJh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WlCV4f6w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lxM3vQLJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3BPjDzDt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UK4DYfku_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_zgSRj8yU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yzpkUQqd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zR1tioAj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dXaMBNlc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_7FhY3dHT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_THzgESsh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_FWFO2Qnc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_JJOMNG5X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_Rhd1RXOk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_se93JTfu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yUm7EJeI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SPjoH6ww_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BbB4NzTC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qa8MKNBA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_0LUn36IL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_93d9NEow_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wPDRIwen_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_l2pmjFGD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_P0qao6mq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6GygdYWT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mnQMFzue_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_J0Aw1NN7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZdI0Ivck_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_lrDiI9zv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_D5KuYNY5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_eRjT80E2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dDEbJ8Vt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Db12SPoT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_U5hTIekm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_OJHZbPO3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_LGc16IzS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aif6iURF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_BW1BbCde_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_zniHikua_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_HvtmZG1d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zyaR2tsU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XQhHtrFZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_qv05Fxur_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_DdtbnK6h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_pWk2LdXc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_6sjQPCWD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ye6gzzpU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MLOezWqf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mMg6G4Xh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_k7STvSrx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Opoi1Ir3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pqEiByb6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Mvk58s3Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_G9qDP3p8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uj2VDRAO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GO3qqPFx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xTesE7EG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_sYM9Ezgd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QPOBrmkW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_yM9wgqN1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_z8B6oh4H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Eo2YqJ4w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8yJ8Czsj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kuSJurYu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ge8TLs3h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_cZT0XEYG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Oy18r7UY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_IxY8TrHQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_W0JnHncm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_xI57EEoz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wFhgSTbw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_sRGELI7C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_JfFW7SM3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_9GAURA5M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zK2dZEXY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5JTTF0Q9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xr7SN6vX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hwQQpCis_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dhl6qz95_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_0H3br9Tt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_dtpMupdU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lJ1XeiOs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9gL8dPUq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8xhnz6i0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7QnOkQKp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QjOyIFBg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5wCx8raP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_u7sDWGzb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yhIl8S69_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6ujRVcCz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZkCOQnwC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_FLEcdpzl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_REm7A2v1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XzsfzmtU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CigExaln_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_4PiGtaXY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DQh66kwM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_7Xj64nIt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_mMDHkx3t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_WKIZMxIU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_wd4aaHWl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Atjjr5Pw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_4aiPamO1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_DnFKYA32_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_AVynXGoa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_iHkgUWFT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CgpvMWv4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TBCXDyIl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Dnwi3z9q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ZZ2NPjNq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BxJRiJcg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8B5Rfnpl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iDMb2IiQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KzAo4N5J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xX0tf3VW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_89Ds0cSN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_blrlwT6X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ShF2MeVj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_lf6hkg4J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_28504LQ5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Qqc0Kj8V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_OwtalwxD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_HfDhW6cJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_aBFsBXi2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WmGo27US_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_viD97Gd0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_V7wT86b2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jAvTbeaR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_pCPLsV7Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_lHWGl6PQ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_TeA2ejZL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FO9ToBzC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yRJDkaDO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_0Jzy3Uam_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_G7wqXs3r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_6BMNVY0i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uBK5zuPU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9kqme3Ix_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rKTP4HMq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_VFF6dCyH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_yq7aWi0u_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_F3RPtqiO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6bNUIxcx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_dyijQEdM_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_vq0Zgjyl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_XhlYwXRI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yrXMWzON_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Mhowtc6M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_bPt3OQ5y_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_Jsos3vsr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ArJlsXZD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_nN6hg82i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_lCLBCtyg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_szdzmsVC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_VXaiSSNG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_i64SnV1z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_r6qDNXUo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7EF0rBfo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qG5vbApg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JwnrtcGs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_gKL5CuXv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_B4ZCEDKS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Mf16Tb4z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_j8IVMQLX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pjkRi71i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kJMqA6bb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5TLDdbtU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ag7BpPvG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_J7E6OqFp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_djl7irNI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GXy0h3GD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rpUeWRA7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xyQo1fgJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_HcMQQf6v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TftJoLoM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_VlpJ69LV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Y7zqPsFo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_uWr8UtCM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kaV66lzu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9KI1KgQx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WdT7DsIo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rPwAF6NA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iuqbwaFp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_u439rKtI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_IBugrX4P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_7nQkN76J_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_PVLS2vjT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Yl9ftnWm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8PqOxj96_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_3eFA57L6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_TEKsBTHx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qmjGxDjN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5JTB1CnY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VeTEEhZR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2XDh955M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_SOP2n1z3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_74snXouF_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_MmmSjL6P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_uFwymiVv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_p2P6Ejwk_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_SDLuEgXa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_ruLiYivG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ZGudY0Bg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ziGlH8Nu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_ruxDxbpW_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_SnPcjEKj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_AiVA4lKC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_2FcbXSEN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_mMNFIr2a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_iMfyCa6t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_9O4YTl9y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BtCRypG0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VoUcTQJg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Yhw4PD9k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_P8bMWNEy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aBCFrkHh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dN8cur6F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hK2d4FX1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cZNe6Gui_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_w0s9SxDD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zwECKGCL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mkpyUmVe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_KkpMx3M2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Q9LUHsou_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_KkTqhQoR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ffJS4mBl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SR1YdxbP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_UMJYRUF0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qQHwlEcX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fiQ3HJkM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zzMxrtWX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_w92atjpf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_noXScCHH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_T17LonnW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4snqFKhG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_PbjuvSYB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_hs3Efvil_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qH2Pw2Pj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5qFMJ2dI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ecp0MdC2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MEKO9DWr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_PCDwwcsf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_K0zmsYHx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_cqZaOmS7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1GbUTxs2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_65n3AyHO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_o4lllOJo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_rxhji8Xx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wOf0zK7i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vrxsASfu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AOEN5TxE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_nQ7I07Cy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Lspe06YS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PVurT9i1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_R3QOL0j2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_wES91LZF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_v7AqcMZB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_W7Koe8Rl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8kznxmlE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oo68xb9Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rjcNlosD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_898994sJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_rCcyOyh9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_hv6v8jKE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_L9XpKhCM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_EdMDY2vk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_n4Fjodh3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1pdLFHww_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XuUGeTvV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5LALTKC7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dliM6CJL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BO3QOqGc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_s5K3Xahf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_vkZu8yhq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hIL9FuTS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ig1NIhU1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_DIc4aqYg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_CA6cLOvd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_ub2Nbkre_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_HNZMYuAb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_uu8fujgb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_fTPTzu9a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_AMJ5s72Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_qb07FtAT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_WlTgaHOs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_px7YBtnF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_IQ3NVDht_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_nsXsCx5R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_Q5XnxoF2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_FpAnLO0Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_Zf5KQYbZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_ZOsrMDgh_sendMessage(HeavyContextInterface *, int, const HvMessage *);

  // objects
  SignalRPole sRPole_Kdd3DDhg;
  SignalDel1 sDel1_XjmkhX9i;
  SignalLine sLine_ejH2bD6t;
  SignalLine sLine_JPVzuI5Q;
  SignalLine sLine_VmB6hsJT;
  SignalLine sLine_Fu2sVHq9;
  SignalBiquad sBiquad_s_n7UdxUlK;
  SignalLine sLine_4mS0j1G8;
  SignalLine sLine_FZgXksBh;
  SignalLine sLine_yQysywQn;
  SignalLine sLine_Ov3p3Isd;
  SignalLine sLine_CtXLtY8F;
  SignalBiquad sBiquad_s_66zrI1S9;
  SignalLine sLine_IUdAKvMj;
  SignalLine sLine_ZgnLLTvh;
  SignalLine sLine_kczgmUZN;
  SignalLine sLine_2SjY66QY;
  SignalLine sLine_pzabNTGe;
  SignalBiquad sBiquad_s_jgjvRuiR;
  ControlBinop cBinop_8Vv93S17;
  ControlBinop cBinop_0gs0arMJ;
  ControlBinop cBinop_MgRQ2ACv;
  ControlBinop cBinop_xMSqkyVN;
  ControlBinop cBinop_XMU1Tazm;
  ControlBinop cBinop_nxgAiqc6;
  ControlBinop cBinop_r2APxwhJ;
  ControlBinop cBinop_1AxX65Et;
  ControlBinop cBinop_iPppAwO6;
  ControlBinop cBinop_ToeTxfqO;
  ControlBinop cBinop_Ajn4g2hx;
  ControlBinop cBinop_eA3owBff;
  ControlVar cVar_LrZYYuEo;
  ControlVar cVar_fG7Soiex;
  ControlVar cVar_8s6DX3g3;
  ControlBinop cBinop_Kp32kwPE;
  ControlBinop cBinop_47ZbPvx5;
  ControlBinop cBinop_CEKzEfgQ;
  ControlBinop cBinop_cC98FeJi;
  ControlBinop cBinop_JGs3l7Zq;
  ControlBinop cBinop_eAUi692P;
  ControlBinop cBinop_tJ8veD64;
  ControlBinop cBinop_5WqBImKu;
  ControlBinop cBinop_JRqpzz41;
  ControlBinop cBinop_k0KmBsDI;
  SignalVarf sVarf_P0Gmrbha;
  ControlVar cVar_bgM6sZl2;
  ControlBinop cBinop_lnJMJnzS;
  ControlBinop cBinop_pPeMaBtc;
  ControlBinop cBinop_yyfJyhJh;
  ControlBinop cBinop_WlCV4f6w;
  ControlBinop cBinop_lxM3vQLJ;
  ControlBinop cBinop_3BPjDzDt;
  ControlBinop cBinop_UK4DYfku;
  SignalVarf sVarf_BOsPhUmL;
  ControlVar cVar_zgSRj8yU;
  ControlBinop cBinop_yUm7EJeI;
  ControlBinop cBinop_BbB4NzTC;
  ControlBinop cBinop_qa8MKNBA;
  ControlBinop cBinop_wPDRIwen;
  ControlBinop cBinop_l2pmjFGD;
  ControlBinop cBinop_P0qao6mq;
  ControlBinop cBinop_6GygdYWT;
  ControlBinop cBinop_mnQMFzue;
  ControlBinop cBinop_ZdI0Ivck;
  ControlBinop cBinop_D5KuYNY5;
  ControlBinop cBinop_eRjT80E2;
  ControlBinop cBinop_Db12SPoT;
  ControlBinop cBinop_U5hTIekm;
  ControlBinop cBinop_OJHZbPO3;
  ControlBinop cBinop_aif6iURF;
  ControlVar cVar_BW1BbCde;
  ControlVar cVar_zniHikua;
  ControlVar cVar_HvtmZG1d;
  ControlBinop cBinop_Ye6gzzpU;
  ControlBinop cBinop_MLOezWqf;
  ControlBinop cBinop_mMg6G4Xh;
  ControlBinop cBinop_Opoi1Ir3;
  ControlBinop cBinop_pqEiByb6;
  ControlBinop cBinop_Mvk58s3Z;
  ControlBinop cBinop_G9qDP3p8;
  ControlBinop cBinop_uj2VDRAO;
  ControlBinop cBinop_GO3qqPFx;
  ControlBinop cBinop_5JTTF0Q9;
  ControlBinop cBinop_hwQQpCis;
  ControlBinop cBinop_dhl6qz95;
  ControlBinop cBinop_lJ1XeiOs;
  ControlBinop cBinop_9gL8dPUq;
  ControlBinop cBinop_8xhnz6i0;
  ControlBinop cBinop_7QnOkQKp;
  ControlBinop cBinop_QjOyIFBg;
  ControlBinop cBinop_u7sDWGzb;
  ControlBinop cBinop_6ujRVcCz;
  ControlBinop cBinop_ZkCOQnwC;
  ControlBinop cBinop_REm7A2v1;
  ControlBinop cBinop_XzsfzmtU;
  ControlBinop cBinop_CigExaln;
  ControlBinop cBinop_DQh66kwM;
  ControlVar cVar_7Xj64nIt;
  ControlVar cVar_mMDHkx3t;
  ControlVar cVar_WKIZMxIU;
  ControlBinop cBinop_CgpvMWv4;
  ControlBinop cBinop_TBCXDyIl;
  ControlBinop cBinop_Dnwi3z9q;
  ControlBinop cBinop_BxJRiJcg;
  ControlBinop cBinop_8B5Rfnpl;
  ControlBinop cBinop_iDMb2IiQ;
  ControlBinop cBinop_KzAo4N5J;
  ControlBinop cBinop_xX0tf3VW;
  ControlBinop cBinop_89Ds0cSN;
  SignalVarf sVarf_BHp5FHSG;
  ControlVar cVar_V7wT86b2;
  ControlDelay cDelay_TeA2ejZL;
  ControlVar cVar_G7wqXs3r;
  ControlBinop cBinop_uBK5zuPU;
  ControlBinop cBinop_9kqme3Ix;
  ControlBinop cBinop_rKTP4HMq;
  ControlVar cVar_VFF6dCyH;
  ControlSlice cSlice_vq0Zgjyl;
  ControlSlice cSlice_XhlYwXRI;
  ControlVar cVar_yrXMWzON;
  ControlVar cVar_Mhowtc6M;
  ControlVar cVar_ArJlsXZD;
  ControlVar cVar_nN6hg82i;
  ControlVar cVar_lCLBCtyg;
  ControlSlice cSlice_szdzmsVC;
  ControlSlice cSlice_VXaiSSNG;
  ControlBinop cBinop_i64SnV1z;
  ControlBinop cBinop_r6qDNXUo;
  ControlBinop cBinop_7EF0rBfo;
  ControlBinop cBinop_qG5vbApg;
  ControlBinop cBinop_JwnrtcGs;
  ControlBinop cBinop_Mf16Tb4z;
  ControlBinop cBinop_j8IVMQLX;
  ControlBinop cBinop_pjkRi71i;
  ControlBinop cBinop_kJMqA6bb;
  ControlBinop cBinop_xyQo1fgJ;
  ControlBinop cBinop_kaV66lzu;
  ControlDelay cDelay_PVLS2vjT;
  ControlVar cVar_TEKsBTHx;
  ControlBinop cBinop_5JTB1CnY;
  ControlBinop cBinop_VeTEEhZR;
  ControlBinop cBinop_2XDh955M;
  ControlVar cVar_SOP2n1z3;
  ControlSlice cSlice_SDLuEgXa;
  ControlSlice cSlice_ruLiYivG;
  ControlVar cVar_ZGudY0Bg;
  ControlVar cVar_ziGlH8Nu;
  ControlVar cVar_AiVA4lKC;
  ControlVar cVar_2FcbXSEN;
  ControlVar cVar_mMNFIr2a;
  ControlSlice cSlice_iMfyCa6t;
  ControlSlice cSlice_9O4YTl9y;
  ControlBinop cBinop_BtCRypG0;
  ControlBinop cBinop_VoUcTQJg;
  ControlBinop cBinop_Yhw4PD9k;
  ControlBinop cBinop_P8bMWNEy;
  ControlBinop cBinop_aBCFrkHh;
  ControlBinop cBinop_cZNe6Gui;
  ControlBinop cBinop_w0s9SxDD;
  ControlBinop cBinop_zwECKGCL;
  ControlBinop cBinop_mkpyUmVe;
  ControlBinop cBinop_qQHwlEcX;
  ControlBinop cBinop_4snqFKhG;
  ControlBinop cBinop_ecp0MdC2;
  ControlBinop cBinop_MEKO9DWr;
  ControlVar cVar_PCDwwcsf;
  ControlVar cVar_K0zmsYHx;
  ControlVar cVar_cqZaOmS7;
  ControlBinop cBinop_1GbUTxs2;
  ControlBinop cBinop_65n3AyHO;
  ControlVar cVar_o4lllOJo;
  ControlIf cIf_rxhji8Xx;
  ControlBinop cBinop_wOf0zK7i;
  ControlBinop cBinop_vrxsASfu;
  ControlBinop cBinop_AOEN5TxE;
  SignalVarf sVarf_wuhRsXdo;
  ControlBinop cBinop_Lspe06YS;
  ControlBinop cBinop_PVurT9i1;
  ControlBinop cBinop_R3QOL0j2;
  ControlBinop cBinop_8kznxmlE;
  ControlBinop cBinop_oo68xb9Z;
  ControlBinop cBinop_XuUGeTvV;
  ControlBinop cBinop_s5K3Xahf;
};

#endif // _HEAVY_CONTEXT_DEARMONDO610_HPP_
